import {MigrationInterface, QueryRunner} from "typeorm";

export class OrderEntity1635298652203 implements MigrationInterface {
    name = 'OrderEntity1635298652203'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "store" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "address" character varying NOT NULL, "phone" character varying NOT NULL, "expire" TIMESTAMP WITH TIME ZONE NOT NULL, "commission" jsonb NOT NULL, "userId" integer, CONSTRAINT "PK_f3172007d4de5ae8e7692759d79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "height"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "length"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "width"`);
        await queryRunner.query(`ALTER TABLE "province" ADD "ghnId" integer`);
        await queryRunner.query(`ALTER TABLE "province" ADD "vtpId" integer`);
        await queryRunner.query(`ALTER TABLE "province" ADD "nameExtensions" jsonb`);
        await queryRunner.query(`ALTER TABLE "district" ADD "ghnId" integer`);
        await queryRunner.query(`ALTER TABLE "district" ADD "vtpId" integer`);
        await queryRunner.query(`ALTER TABLE "district" ADD "nameExtensions" jsonb`);
        await queryRunner.query(`ALTER TABLE "ward" ADD "ghnCode" character varying`);
        await queryRunner.query(`ALTER TABLE "ward" ADD "vtpId" integer`);
        await queryRunner.query(`ALTER TABLE "order" ADD "height" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "order" ADD "length" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "order" ADD "width" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "order" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "district" DROP CONSTRAINT "FK_23a21b38208367a242b1dd3a424"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "province_id_seq" OWNED BY "province"."id"`);
        await queryRunner.query(`ALTER TABLE "province" ALTER COLUMN "id" SET DEFAULT nextval('"province_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "province" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "province" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "province" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "province" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "province" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ward" DROP CONSTRAINT "FK_19a3bc9b3be291e8b9bc2bb623b"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "district_id_seq" OWNED BY "district"."id"`);
        await queryRunner.query(`ALTER TABLE "district" ALTER COLUMN "id" SET DEFAULT nextval('"district_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "district" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_5ca267c961911128555d353737a"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" DROP CONSTRAINT "FK_7d91b6568bcd354f12f4d90b447"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_9ba869b4b0dc3e85654051bc6ab"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP CONSTRAINT "FK_c028f9f26aada1364010cc05826"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "ward_id_seq" OWNED BY "ward"."id"`);
        await queryRunner.query(`ALTER TABLE "ward" ALTER COLUMN "id" SET DEFAULT nextval('"ward_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "ward" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ward" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ward" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ward" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ward" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_62fcc319202f6ec1f6819e1d5f5"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_48a28cfd87e34f3df960bb374ba"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" DROP CONSTRAINT "FK_8e771926d9657288a123bab89b8"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_293ad75db4c3b2aa62996c75ad1"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "merchant_id_seq" OWNED BY "merchant"."id"`);
        await queryRunner.query(`ALTER TABLE "merchant" ALTER COLUMN "id" SET DEFAULT nextval('"merchant_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "merchant" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "merchant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "merchant" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "merchant" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_441bb7dca61539b068860ee4e8a"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "merchant_address_id_seq" OWNED BY "merchant_address"."id"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ALTER COLUMN "id" SET DEFAULT nextval('"merchant_address_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "merchant_address" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant_address" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_618194d24a7ea86a165d7ec628e"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP CONSTRAINT "FK_569b30aa4b0a1ad42bcd30916aa"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" DROP CONSTRAINT "FK_629285753982a3e66feee127c74"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "product_category_id_seq" OWNED BY "product_category"."id"`);
        await queryRunner.query(`ALTER TABLE "product_category" ALTER COLUMN "id" SET DEFAULT nextval('"product_category_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "product_category" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_cff8eff4c72e7c4cb5bf045447c"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "voucher_id_seq" OWNED BY "voucher"."id"`);
        await queryRunner.query(`ALTER TABLE "voucher" ALTER COLUMN "id" SET DEFAULT nextval('"voucher_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "voucher" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "voucher" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "voucher" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "voucher" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "voucher" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "product_variant_id_seq" OWNED BY "product_variant"."id"`);
        await queryRunner.query(`ALTER TABLE "product_variant" ALTER COLUMN "id" SET DEFAULT nextval('"product_variant_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "product_variant" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP CONSTRAINT "FK_8045e3f384ced706b25bc18867f"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "product_category_attribute_id_seq" OWNED BY "product_category_attribute"."id"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ALTER COLUMN "id" SET DEFAULT nextval('"product_category_attribute_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "product_attribute_id_seq" OWNED BY "product_attribute"."id"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ALTER COLUMN "id" SET DEFAULT nextval('"product_attribute_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "product_model_id_seq" OWNED BY "product_model"."id"`);
        await queryRunner.query(`ALTER TABLE "product_model" ALTER COLUMN "id" SET DEFAULT nextval('"product_model_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "product_model" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_model" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_model" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_model" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_model" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP CONSTRAINT "FK_6e420052844edf3a5506d863ce6"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP CONSTRAINT "FK_773130e333405f9549d7e7daa34"`);
        await queryRunner.query(`ALTER TABLE "product_model" DROP CONSTRAINT "FK_0d1428dc1db13055b392442b1f9"`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_073c85ed133e05241040bd70f02"`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP CONSTRAINT "FK_da6ae7ddcc605d145e88b8cfeaa"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "product_id_seq" OWNED BY "product"."id"`);
        await queryRunner.query(`ALTER TABLE "product" ALTER COLUMN "id" SET DEFAULT nextval('"product_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "product" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "permission_role" DROP CONSTRAINT "FK_1dd59c61aec4fc206bc43a31153"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "role_id_seq" OWNED BY "role"."id"`);
        await queryRunner.query(`ALTER TABLE "role" ALTER COLUMN "id" SET DEFAULT nextval('"role_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "role" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_329b8ae12068b23da547d3b4798"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_ab57b9b261d32985dab19184382"`);
        await queryRunner.query(`ALTER TABLE "voucher" DROP CONSTRAINT "FK_80a57d757e0be8225f261c7994f"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_caabe91507b3379c7ba73637b84"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP CONSTRAINT "FK_2aa99b101de6fb5f3089bd4b7a9"`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP CONSTRAINT "FK_a9a463c73a22d136f99b269940c"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "user_id_seq" OWNED BY "user"."id"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "id" SET DEFAULT nextval('"user_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "lastLogin"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "lastLogin" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "nationalIssueDate"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "nationalIssueDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "dob"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "dob" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_enum" RENAME TO "user_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('active', 'inactive', 'banned', 'deleted')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "status" TYPE "public"."user_status_enum" USING "status"::"text"::"public"."user_status_enum"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum_old"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "order_product_id_seq" OWNED BY "order_product"."id"`);
        await queryRunner.query(`ALTER TABLE "order_product" ALTER COLUMN "id" SET DEFAULT nextval('"order_product_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "order_product" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_3fb066240db56c9558a91139431"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "order_id_seq" OWNED BY "order"."id"`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "id" SET DEFAULT nextval('"order_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "shippingFee" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "shippingDiscount" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permission_role" DROP CONSTRAINT "FK_1886001bdced4ea977b9f1b97c1"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "permission_id_seq" OWNED BY "permission"."id"`);
        await queryRunner.query(`ALTER TABLE "permission" ALTER COLUMN "id" SET DEFAULT nextval('"permission_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "permission" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "product_post_id_seq" OWNED BY "product_post"."id"`);
        await queryRunner.query(`ALTER TABLE "product_post" ALTER COLUMN "id" SET DEFAULT nextval('"product_post_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "product_post" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "shipping_address_id_seq" OWNED BY "shipping_address"."id"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ALTER COLUMN "id" SET DEFAULT nextval('"shipping_address_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "district" ADD CONSTRAINT "FK_23a21b38208367a242b1dd3a424" FOREIGN KEY ("provinceId") REFERENCES "province"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ward" ADD CONSTRAINT "FK_19a3bc9b3be291e8b9bc2bb623b" FOREIGN KEY ("districtId") REFERENCES "district"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ADD CONSTRAINT "FK_7d91b6568bcd354f12f4d90b447" FOREIGN KEY ("wardId") REFERENCES "ward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ADD CONSTRAINT "FK_8e771926d9657288a123bab89b8" FOREIGN KEY ("merchantId") REFERENCES "merchant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD CONSTRAINT "FK_569b30aa4b0a1ad42bcd30916aa" FOREIGN KEY ("parentId") REFERENCES "product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voucher" ADD CONSTRAINT "FK_80a57d757e0be8225f261c7994f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD CONSTRAINT "FK_6e420052844edf3a5506d863ce6" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ADD CONSTRAINT "FK_629285753982a3e66feee127c74" FOREIGN KEY ("productCategoryId") REFERENCES "product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD CONSTRAINT "FK_773130e333405f9549d7e7daa34" FOREIGN KEY ("productsId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD CONSTRAINT "FK_8045e3f384ced706b25bc18867f" FOREIGN KEY ("productCategoryAttributeId") REFERENCES "product_category_attribute"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_model" ADD CONSTRAINT "FK_0d1428dc1db13055b392442b1f9" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_329b8ae12068b23da547d3b4798" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_62fcc319202f6ec1f6819e1d5f5" FOREIGN KEY ("merchantId") REFERENCES "merchant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_618194d24a7ea86a165d7ec628e" FOREIGN KEY ("productCategoryId") REFERENCES "product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c86f56da7bb30c073e3cbed4e50" FOREIGN KEY ("parentId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_ab57b9b261d32985dab19184382" FOREIGN KEY ("referralId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_48a28cfd87e34f3df960bb374ba" FOREIGN KEY ("merchantId") REFERENCES "merchant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_5ca267c961911128555d353737a" FOREIGN KEY ("wardId") REFERENCES "ward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_3fb066240db56c9558a91139431" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_073c85ed133e05241040bd70f02" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_293ad75db4c3b2aa62996c75ad1" FOREIGN KEY ("merchantId") REFERENCES "merchant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_441bb7dca61539b068860ee4e8a" FOREIGN KEY ("merchantAddressId") REFERENCES "merchant_address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_9ba869b4b0dc3e85654051bc6ab" FOREIGN KEY ("wardId") REFERENCES "ward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_cff8eff4c72e7c4cb5bf045447c" FOREIGN KEY ("voucherId") REFERENCES "voucher"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD CONSTRAINT "FK_e15b4a73a3e53311433968993cc" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD CONSTRAINT "FK_2941cb76af683941a1fd0b69dac" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD CONSTRAINT "FK_a9a463c73a22d136f99b269940c" FOREIGN KEY ("modifiedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD CONSTRAINT "FK_da6ae7ddcc605d145e88b8cfeaa" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD CONSTRAINT "FK_2aa99b101de6fb5f3089bd4b7a9" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD CONSTRAINT "FK_c028f9f26aada1364010cc05826" FOREIGN KEY ("wardId") REFERENCES "ward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store" ADD CONSTRAINT "FK_3f82dbf41ae837b8aa0a27d29c3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permission_role" ADD CONSTRAINT "FK_1886001bdced4ea977b9f1b97c1" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "permission_role" ADD CONSTRAINT "FK_1dd59c61aec4fc206bc43a31153" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "permission_role" DROP CONSTRAINT "FK_1dd59c61aec4fc206bc43a31153"`);
        await queryRunner.query(`ALTER TABLE "permission_role" DROP CONSTRAINT "FK_1886001bdced4ea977b9f1b97c1"`);
        await queryRunner.query(`ALTER TABLE "store" DROP CONSTRAINT "FK_3f82dbf41ae837b8aa0a27d29c3"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP CONSTRAINT "FK_c028f9f26aada1364010cc05826"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP CONSTRAINT "FK_2aa99b101de6fb5f3089bd4b7a9"`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP CONSTRAINT "FK_da6ae7ddcc605d145e88b8cfeaa"`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP CONSTRAINT "FK_a9a463c73a22d136f99b269940c"`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP CONSTRAINT "FK_2941cb76af683941a1fd0b69dac"`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP CONSTRAINT "FK_e15b4a73a3e53311433968993cc"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_cff8eff4c72e7c4cb5bf045447c"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_9ba869b4b0dc3e85654051bc6ab"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_caabe91507b3379c7ba73637b84"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_441bb7dca61539b068860ee4e8a"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_293ad75db4c3b2aa62996c75ad1"`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_073c85ed133e05241040bd70f02"`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP CONSTRAINT "FK_3fb066240db56c9558a91139431"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_5ca267c961911128555d353737a"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_48a28cfd87e34f3df960bb374ba"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_ab57b9b261d32985dab19184382"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c86f56da7bb30c073e3cbed4e50"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_618194d24a7ea86a165d7ec628e"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_62fcc319202f6ec1f6819e1d5f5"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_329b8ae12068b23da547d3b4798"`);
        await queryRunner.query(`ALTER TABLE "product_model" DROP CONSTRAINT "FK_0d1428dc1db13055b392442b1f9"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP CONSTRAINT "FK_8045e3f384ced706b25bc18867f"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP CONSTRAINT "FK_773130e333405f9549d7e7daa34"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" DROP CONSTRAINT "FK_629285753982a3e66feee127c74"`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP CONSTRAINT "FK_6e420052844edf3a5506d863ce6"`);
        await queryRunner.query(`ALTER TABLE "voucher" DROP CONSTRAINT "FK_80a57d757e0be8225f261c7994f"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP CONSTRAINT "FK_569b30aa4b0a1ad42bcd30916aa"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" DROP CONSTRAINT "FK_8e771926d9657288a123bab89b8"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" DROP CONSTRAINT "FK_7d91b6568bcd354f12f4d90b447"`);
        await queryRunner.query(`ALTER TABLE "ward" DROP CONSTRAINT "FK_19a3bc9b3be291e8b9bc2bb623b"`);
        await queryRunner.query(`ALTER TABLE "district" DROP CONSTRAINT "FK_23a21b38208367a242b1dd3a424"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ALTER COLUMN "id" SET DEFAULT nextval('shipping_address_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "shipping_address_id_seq"`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_post" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_post" ALTER COLUMN "id" SET DEFAULT nextval('product_post_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "product_post" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "product_post_id_seq"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permission" ALTER COLUMN "id" SET DEFAULT nextval('permission_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "permission" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "permission_id_seq"`);
        await queryRunner.query(`ALTER TABLE "permission_role" ADD CONSTRAINT "FK_1886001bdced4ea977b9f1b97c1" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "shippingDiscount" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "shippingFee" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "status" SET DEFAULT 'processing'`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "id" SET DEFAULT nextval('order_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "order_id_seq"`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_3fb066240db56c9558a91139431" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_product" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_product" ALTER COLUMN "id" SET DEFAULT nextval('order_product_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "order_product" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "order_product_id_seq"`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum_old" AS ENUM('active', 'inactive', 'banned')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "status" TYPE "public"."user_status_enum_old" USING "status"::"text"::"public"."user_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "status" SET DEFAULT 'inactive'`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_enum_old" RENAME TO "user_status_enum"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "dob"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "dob" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "nationalIssueDate"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "nationalIssueDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "lastLogin"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "lastLogin" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "id" SET DEFAULT nextval('user_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "user_id_seq"`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD CONSTRAINT "FK_a9a463c73a22d136f99b269940c" FOREIGN KEY ("modifiedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD CONSTRAINT "FK_2aa99b101de6fb5f3089bd4b7a9" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voucher" ADD CONSTRAINT "FK_80a57d757e0be8225f261c7994f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_ab57b9b261d32985dab19184382" FOREIGN KEY ("referralId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_329b8ae12068b23da547d3b4798" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ALTER COLUMN "id" SET DEFAULT nextval('role_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "role" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "role_id_seq"`);
        await queryRunner.query(`ALTER TABLE "permission_role" ADD CONSTRAINT "FK_1dd59c61aec4fc206bc43a31153" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product" ALTER COLUMN "id" SET DEFAULT nextval('product_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "product" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "product_id_seq"`);
        await queryRunner.query(`ALTER TABLE "product_post" ADD CONSTRAINT "FK_da6ae7ddcc605d145e88b8cfeaa" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_product" ADD CONSTRAINT "FK_073c85ed133e05241040bd70f02" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_model" ADD CONSTRAINT "FK_0d1428dc1db13055b392442b1f9" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD CONSTRAINT "FK_773130e333405f9549d7e7daa34" FOREIGN KEY ("productsId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD CONSTRAINT "FK_6e420052844edf3a5506d863ce6" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_model" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_model" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_model" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_model" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_model" ALTER COLUMN "id" SET DEFAULT nextval('product_model_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "product_model" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "product_model_id_seq"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_attribute" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ALTER COLUMN "id" SET DEFAULT nextval('product_attribute_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "product_attribute_id_seq"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ALTER COLUMN "id" SET DEFAULT nextval('product_category_attribute_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "product_category_attribute_id_seq"`);
        await queryRunner.query(`ALTER TABLE "product_attribute" ADD CONSTRAINT "FK_8045e3f384ced706b25bc18867f" FOREIGN KEY ("productCategoryAttributeId") REFERENCES "product_category_attribute"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_variant" ALTER COLUMN "id" SET DEFAULT nextval('product_variant_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "product_variant" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "product_variant_id_seq"`);
        await queryRunner.query(`ALTER TABLE "voucher" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "voucher" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "voucher" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "voucher" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "voucher" ALTER COLUMN "id" SET DEFAULT nextval('voucher_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "voucher" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "voucher_id_seq"`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_cff8eff4c72e7c4cb5bf045447c" FOREIGN KEY ("voucherId") REFERENCES "voucher"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_category" ALTER COLUMN "id" SET DEFAULT nextval('product_category_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "product_category" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "product_category_id_seq"`);
        await queryRunner.query(`ALTER TABLE "product_category_attribute" ADD CONSTRAINT "FK_629285753982a3e66feee127c74" FOREIGN KEY ("productCategoryId") REFERENCES "product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD CONSTRAINT "FK_569b30aa4b0a1ad42bcd30916aa" FOREIGN KEY ("parentId") REFERENCES "product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_618194d24a7ea86a165d7ec628e" FOREIGN KEY ("productCategoryId") REFERENCES "product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchant_address" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant_address" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ALTER COLUMN "id" SET DEFAULT nextval('merchant_address_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "merchant_address_id_seq"`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_441bb7dca61539b068860ee4e8a" FOREIGN KEY ("merchantAddressId") REFERENCES "merchant_address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchant" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "merchant" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "merchant" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant" ALTER COLUMN "id" SET DEFAULT nextval('merchant_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "merchant" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "merchant_id_seq"`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_293ad75db4c3b2aa62996c75ad1" FOREIGN KEY ("merchantId") REFERENCES "merchant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ADD CONSTRAINT "FK_8e771926d9657288a123bab89b8" FOREIGN KEY ("merchantId") REFERENCES "merchant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_48a28cfd87e34f3df960bb374ba" FOREIGN KEY ("merchantId") REFERENCES "merchant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_62fcc319202f6ec1f6819e1d5f5" FOREIGN KEY ("merchantId") REFERENCES "merchant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ward" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ward" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ward" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ward" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ward" ALTER COLUMN "id" SET DEFAULT nextval('ward_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "ward" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "ward_id_seq"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD CONSTRAINT "FK_c028f9f26aada1364010cc05826" FOREIGN KEY ("wardId") REFERENCES "ward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_9ba869b4b0dc3e85654051bc6ab" FOREIGN KEY ("wardId") REFERENCES "ward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchant_address" ADD CONSTRAINT "FK_7d91b6568bcd354f12f4d90b447" FOREIGN KEY ("wardId") REFERENCES "ward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_5ca267c961911128555d353737a" FOREIGN KEY ("wardId") REFERENCES "ward"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "district" ALTER COLUMN "id" SET DEFAULT nextval('district_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "district" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "district_id_seq"`);
        await queryRunner.query(`ALTER TABLE "ward" ADD CONSTRAINT "FK_19a3bc9b3be291e8b9bc2bb623b" FOREIGN KEY ("districtId") REFERENCES "district"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "province" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "province" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "province" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "province" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "province" ALTER COLUMN "id" SET DEFAULT nextval('province_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "province" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "province_id_seq"`);
        await queryRunner.query(`ALTER TABLE "district" ADD CONSTRAINT "FK_23a21b38208367a242b1dd3a424" FOREIGN KEY ("provinceId") REFERENCES "province"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "width"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "length"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "height"`);
        await queryRunner.query(`ALTER TABLE "ward" DROP COLUMN "vtpId"`);
        await queryRunner.query(`ALTER TABLE "ward" DROP COLUMN "ghnCode"`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "nameExtensions"`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "vtpId"`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "ghnId"`);
        await queryRunner.query(`ALTER TABLE "province" DROP COLUMN "nameExtensions"`);
        await queryRunner.query(`ALTER TABLE "province" DROP COLUMN "vtpId"`);
        await queryRunner.query(`ALTER TABLE "province" DROP COLUMN "ghnId"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "width" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "product" ADD "length" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "product" ADD "height" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP TABLE "store"`);
    }

}
